plugins {
    id 'java'
    id 'net.fabricmc.fabric-loom-remap' version '1.17.20'
    id 'ploceus' version '1.17.7'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    //accessWidenerPath = file("src/main/resources/fancystats.accesswidener")
}

ploceus {
    setIntermediaryGeneration(2)
}

repositories {

}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    //modImplementation files("libs/restonic4_whimsical_lib-0.1+mc1.0.0.jar")

    clientExceptions ploceus.raven(project.client_raven_build, 'client')
    serverExceptions ploceus.raven(project.server_raven_build, 'server')
    clientSignatures ploceus.sparrow(project.client_sparrow_build, 'client')
    serverSignatures ploceus.sparrow(project.server_sparrow_build, 'server')
    clientNests ploceus.nests(project.client_nests_build, 'client')
    serverNests ploceus.nests(project.server_nests_build, 'server')
    mappings ploceus.featherMappings(project.feather_build)

    ploceus.dependOsl(project.osl_version)
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = 'UTF-8'
    it.options.release = 8
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8

    withSourcesJar()
}

jar {
    from('LICENSE.txt') {
        rename { "${it}_${base.archivesName.get()}" }
    }
}